//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int materialsID { get; set; }
        public string materialsName { get; set; }
        public byte[] dropLocation { get; set; }
        public Nullable<int> highRankDrop { get; set; }
        public Nullable<int> lowRankDrop { get; set; }
    }
}
