//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public int monsterID { get; set; }
        public string monsterName { get; set; }
        public string monsterWeakness { get; set; }
        public Nullable<int> monsterDamage { get; set; }
    }
}
