//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        public int weaponsID { get; set; }
        public string weaponName { get; set; }
        public byte[] weaponType { get; set; }
        public string weaponTree { get; set; }
        public Nullable<int> weaponLevel { get; set; }
    }
}
